#deployment not supports parameters
#we have to write same code for each app those many times.
#so we came with HELM CHARTS.

#selector label is use for endpoint generation. when selector names of pod & service matches then service creates endpoint


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    ephoc: "{{ .Values.ephoc }}"
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        ephoc: "{{ .Values.ephoc }}"
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: 041583668323.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}
        imagePullPolicy: Always
        {{- if .Values.configMap.enabled -}}
        envFrom :
        - configMapRef :
            name : {{ .Values.appName }}
        {{- end -}}
        { { - if .Values.externalSecret.enabled } }
        - secretRef :
            name : { { .Values.appName } }
        { { - end } }

